# Generated by Django 3.2.4 on 2021-06-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.JSONField(blank=True, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='sounds')),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('last_user', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
