# Generated by Django 3.2.4 on 2021-06-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_audio_annotater'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatedAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to='rated_sounds')),
                ('window_size', models.FloatField(default=1)),
                ('lower_limit', models.IntegerField(default=1)),
                ('upper_limit', models.IntegerField(default=5)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
    ]
