# Generated by Django 3.2.4 on 2021-06-25 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_ratedaudio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('suggested_label', models.CharField(blank=True, max_length=100, null=True)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_ratings', to='core.ratedaudio')),
                ('rater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rater_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
