# Generated by Django 3.2.4 on 2021-07-04 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratedaudio',
            old_name='window_size',
            new_name='rating_precision',
        ),
        migrations.AlterField(
            model_name='audio',
            name='annotater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotater_audios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rater_ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
