# Generated by Django 3.2.4 on 2021-07-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210704_1223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audio',
        ),
    ]
