# Generated by Django 3.2.4 on 2021-07-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
