# Generated by Django 3.2.4 on 2021-07-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ratedaudio_rating_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratedaudio',
            name='avg_rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
